event:
    movie_file:
        path: MOVIE_PATH
        add:
            url: DISPATCH_URL
        unlink:
            url: DISPATCH_URL
    command_file:
        path: COMMAND_PATH
        add:
            exec: DISPATCH_EXEC
        process_end:
            url: DISPATCH_URL