env:
    movie_path: ./movie
    command_path: ./command
    dispatch_url: http://devnull-as-a-service.com/dev/null
    dispatch_exec: echo
    handbrake_workdir: ./work
    handbrake_outdir: ./out
    handbrake_enddir: ./out
event:
    movie_file:
        root: movie_path
        pattern: "**/*"
        add:
            url: dispatch_url
        unlink:
            url: dispatch_url
    command_file:
        root: command_path
        pattern: "handbrake/*"
        add:
            content_type: json
            handbrake:
                workdir: handbrake_workdir
                outdir: handbrake_outdir 
                enddir: handbrake_enddir 
                extension: .mp4
                options:
                    large-file: true
                    optimize: true
                    encoder: x264
                    encopts: b-adapt=2:rc-lookahead=50
                    quality: 22
                    two-pass: true
                    turbo: true
                    vfr: true
                    audio: 1
                    aencoder: faac
                    ab: 160
                    mixdown: stereo
                    arate: Auto
                    crop: 0:0:0:0
                    strict-anamorphic: true
                    decomb: true
        process_end:
            url: dispatch_url
        process_error:
            url: dispatch_url